---
language: node_js
node_js:
  - "node"
env:
  - TEST_DIR=client
  #- TEST_DIR=server
before_install:
  - cd $TEST_DIR
install:
  - npm install
script:
  - npm test
  - sh -c "if [ '$TEST_DIR' = 'client' ]; then npm run build; fi"
